import Header from "@/components/layouts/header/index.tsx";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import localFont from "next/font/local";
import { ReactNode } from "react";
import "../globals.css";

const abcDiatype = localFont({
  src: [
    {
      path: "../../assets/fonts/ABCDiatypeCyrillic/ABCDiatypeCyrillic-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../assets/fonts/ABCDiatypeCyrillic/ABCDiatypeCyrillic-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../assets/fonts/ABCDiatypeCyrillic/ABCDiatypeCyrillic-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "fallback",
  variable: "--font-abc-diatype",
});

export const metadata: Metadata = {
  title: "Linken Sphere",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale } = await params;

  return (
    <html lang={locale} className={`${abcDiatype.variable} font-diatype h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <NextIntlClientProvider>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
